.TH ansir 1 "April 2026" "ansir 0.5.0" "User Commands"
.SH NAME
ansir \- Convert PNGs to colorful terminal ANSI art
.SH SYNOPSIS
.B ansir
.RI [ options ] " <input.png>"
.SH DESCRIPTION
.B ansir
is a tool to convert PNG images into colorful ANSI art for terminal display.
.SH OPTIONS
.TP
.BR -h , --help
Show help message and exit.
.TP
.BR -o , --output <file>
Write output to file instead of stdout.
.TP
.BR -s , --scale <factor>
Set scale factor for output art.
.SH AUTHOR
Bill Dwyer <themadcreator@github>
.SH LICENSE
Apache-2.0
