// Generated by CoffeeScript 2.7.0
(function() {
  var ColorTable, Octree, ansi, chroma, render;

  chroma = require('chroma-js');

  ansi = require('../ansi-codes');

  Octree = require('../octree');

  ColorTable = class ColorTable {
    constructor(config1) {
      var ansiCode, i, len, ref;
      this.config = config1;
      this.tree = new Octree();
      ref = this.config.ansiCodes;
      for (i = 0, len = ref.length; i < len; i++) {
        ansiCode = ref[i];
        this.tree.insert(new Octree.Point(...ansiCode.color.lab()), ansiCode);
      }
    }

    // Finds the nearest color by using euclidean distance in CIELAB colorspace.
    // We insert all the colors in the color table into an octree so that nearest
    // neighbor searches are very fast.
    getNearest(color) {
      if (color.alpha() < this.config.alphaCutoff) {
        return null;
      }
      return this.tree.nearest(new Octree.Point(...color.lab())).value.bg;
    }

  };

  render = function(image, config) {
    var color, colorTable, i, j, line, ref, ref1, x, y;
    colorTable = new ColorTable(config);
    for (y = i = 0, ref = image.height; (0 <= ref ? i <= ref : i >= ref); y = 0 <= ref ? ++i : --i) {
      line = [];
      for (x = j = 0, ref1 = image.width; (0 <= ref1 ? j <= ref1 : j >= ref1); x = 0 <= ref1 ? ++j : --j) {
        color = colorTable.getNearest(image.colorAt(x, y));
        line.push({
          char: '\u0020',
          fg: null,
          bg: color
        });
      }
      config.write(ansi.joinLineEscapes(line) + '\n');
    }
    config.write(ansi.ANSI_RESET);
  };

  module.exports = {render};

}).call(this);
