// Generated by CoffeeScript 2.7.0
(function() {
  var BrailleColorTable, Octree, _, ansi, chroma, render;

  _ = require('lodash');

  chroma = require('chroma-js');

  ansi = require('../ansi-codes');

  Octree = require('../octree');

  BrailleColorTable = (function() {
    class BrailleColorTable {
      constructor(config1) {
        var ansiCode, j, len, ref;
        this.config = config1;
        this.tree = new Octree();
        ref = this.config.ansiCodes;
        for (j = 0, len = ref.length; j < len; j++) {
          ansiCode = ref[j];
          this.tree.insert(new Octree.Point(...ansiCode.color.lab()), ansiCode);
        }
        return;
      }

      getTransparentDistance(colors) {
        return colors.map((c) => {
          if (c.alpha() < this.config.alphaCutoff) {
            return 0;
          } else {
            return 100;
          }
        }).reduce(function(a, b) {
          return a + b;
        });
      }

      getNearestColor(colors) {
        var lab, labs, nearest;
        // Get nearest point to CIELAB centroid
        labs = colors.map(function(c) {
          return new Octree.Point(...c.lab());
        });
        lab = Octree.Point.centroid(labs);
        nearest = this.tree.nearest(lab);
        nearest.distance *= colors.length;
        // # Compare to transparent
        // transparentDistance = @getTransparentDistance(colors)
        // if transparentDistance is 0
        //   return {
        //     distance : transparentDistance
        //     value    : null
        //   }

        // Rescale distance
        return nearest;
      }

      decodeBrailleOffset(pixels, offset, invert = false) {
        return _.filter(pixels, function(p, i) {
          var mask;
          mask = BrailleColorTable.UTF8_BRAILLE_MAP[i];
          return ((offset & mask) === mask) ^ invert;
        });
      }

      /*
      Finds the best foreground/background match to the four pixel block.

      Pixel layout:
        [p0][p1]
        [p2][p3]
      */
      getNearest(pixels) {
        var best, bgPixels, cand, candidates, fgPixels, i, j, offset, ref, ref1;
        candidates = [
          {
            char: '\u0020',
            fg: {
              distance: this.getTransparentDistance(pixels),
              value: null
            },
            bg: {
              distance: 0,
              value: null
            }
          }
        ];
        for (i = j = 0x40; j <= 255; i = ++j) {
          offset = 0x2800 + i;
          fgPixels = this.decodeBrailleOffset(pixels, i, false);
          bgPixels = this.decodeBrailleOffset(pixels, i, true);
          candidates.push(cand = {
            char: String.fromCharCode(offset),
            fg: this.getNearestColor(fgPixels),
            bg: this.getNearestColor(bgPixels)
          });
        }
        best = _.minBy(candidates, function(c) {
          return c.fg.distance + c.bg.distance;
        });
        return {
          fg: (ref = best.fg.value) != null ? ref.fg : void 0,
          bg: (ref1 = best.bg.value) != null ? ref1.bg : void 0,
          char: best.char
        };
      }

    };

    BrailleColorTable.UTF8_BRAILLE_MAP = [0x1, 0x8, 0x2, 0x10, 0x4, 0x20, 0x40, 0x80];

    return BrailleColorTable;

  }).call(this);

  render = function(image, config) {
    var colorTable, j, k, line, pixels, ref, ref1, x, y;
    colorTable = new BrailleColorTable(config);
    for (y = j = 0, ref = image.height - 4; j < ref; y = j += 4) {
      line = [];
      for (x = k = 0, ref1 = image.width - 2; k < ref1; x = k += 2) {
        pixels = [image.colorAt(x, y), image.colorAt(x + 1, y), image.colorAt(x, y + 1), image.colorAt(x + 1, y + 1), image.colorAt(x, y + 2), image.colorAt(x + 1, y + 2), image.colorAt(x, y + 3), image.colorAt(x + 1, y + 3)];
        line.push(colorTable.getNearest(pixels));
      }
      config.write(ansi.joinLineEscapes(line) + '\n');
    }
    config.write(ansi.ANSI_RESET);
  };

  module.exports = {
    render,
    charHeight: 1
  };

}).call(this);
