// Generated by CoffeeScript 2.7.0
(function() {
  var ColorTable, Octree, ansi, chroma, render;

  chroma = require('chroma-js');

  ansi = require('../ansi-codes');

  Octree = require('../octree');

  ColorTable = (function() {
    class ColorTable {
      constructor(config1) {
        var ansiCode, blockChar, color, entry, i, j, k, len, len1, opacity, ref, ref1;
        this.config = config1;
        this.tree = new Octree();
        ref = this.config.ansiCodes;
        for (j = 0, len = ref.length; j < len; j++) {
          ansiCode = ref[j];
          ref1 = ColorTable.UTF8_SHADED_BLOCK_CHARS;
          for (i = k = 0, len1 = ref1.length; k < len1; i = ++k) {
            blockChar = ref1[i];
            opacity = (i + 1) / 4.0;
            color = chroma.mix(this.config.terminalBackground, ansiCode.color, opacity, 'hsl');
            entry = {blockChar, ansiCode};
            this.tree.insert(new Octree.Point(...color.lab()), entry);
          }
        }
        return;
      }

      // Finds the nearest color by using euclidean distance in CIELAB colorspace.
      // We insert all the colors in the color table into an octree so that nearest
      // neighbor searches are very fast.
      getNearest(color) {
        if (color.alpha() < this.config.alphaCutoff) {
          return null;
        }
        return this.tree.nearest(new Octree.Point(...color.lab())).value;
      }

    };

    ColorTable.UTF8_SHADED_BLOCK_CHARS = [
      '\u2591', // ░ LIGHT SHADE
      '\u2592', // ▒ MEDIUM SHADE
      '\u2593', // ▓ DARK SHADE
      '\u2588' // █ FULL BLOCK
    ];

    return ColorTable;

  }).call(this);

  render = function(image, config) {
    var colorTable, j, k, line, nearest, ref, ref1, x, y;
    colorTable = new ColorTable(config);
    for (y = j = 0, ref = image.height; (0 <= ref ? j <= ref : j >= ref); y = 0 <= ref ? ++j : --j) {
      line = [];
      for (x = k = 0, ref1 = image.width; (0 <= ref1 ? k <= ref1 : k >= ref1); x = 0 <= ref1 ? ++k : --k) {
        nearest = colorTable.getNearest(image.colorAt(x, y));
        if (nearest != null) {
          line.push({
            char: nearest.blockChar,
            fg: nearest.ansiCode.fg,
            bg: null
          });
        } else {
          line.push({
            char: '\u0020',
            fg: null,
            bg: null
          });
        }
      }
      config.write(ansi.joinLineEscapes(line) + '\n');
    }
    config.write(ansi.ANSI_RESET);
  };

  module.exports = {render};

}).call(this);
