// Generated by CoffeeScript 2.7.0
(function() {
  var Octree, SubBlockColorTable, _, ansi, chroma, render;

  _ = require('lodash');

  chroma = require('chroma-js');

  ansi = require('../ansi-codes');

  Octree = require('../octree');

  SubBlockColorTable = (function() {
    class SubBlockColorTable {
      constructor(config1) {
        var ansiCode, i, len, ref;
        this.config = config1;
        this.tree = new Octree();
        ref = this.config.ansiCodes;
        for (i = 0, len = ref.length; i < len; i++) {
          ansiCode = ref[i];
          this.tree.insert(new Octree.Point(...ansiCode.color.lab()), ansiCode);
        }
        return;
      }

      getTransparentDistance(colors) {
        return colors.map((c) => {
          if (c.alpha() < this.config.alphaCutoff) {
            return 0;
          } else {
            return 100;
          }
        }).reduce(function(a, b) {
          return a + b;
        });
      }

      getNearestColor(colors) {
        var lab, labs, nearest, transparentDistance;
        // Get nearest point to CIELAB centroid
        labs = colors.map(function(c) {
          return new Octree.Point(...c.lab());
        });
        lab = Octree.Point.centroid(labs);
        nearest = this.tree.nearest(lab);
        nearest.distance *= colors.length;
        // Compare to transparent
        transparentDistance = this.getTransparentDistance(colors);
        if (transparentDistance === 0) {
          return {
            distance: transparentDistance,
            value: null
          };
        }
        // Rescale distance
        return nearest;
      }

      /*
      Finds the best foreground/background match to the four pixel block.

      Pixel layout:
        [p0][p1]
        [p2][p3]
      */
      getNearest([p0, p1, p2, p3]) {
        var best, candidates, ref, ref1;
        candidates = [
          {
            char: '\u0020',
            fg: {
              distance: this.getTransparentDistance([p0,
          p1,
          p2,
          p3]),
              value: null
            },
            bg: {
              distance: 0,
              value: null
            }
          },
          {
            char: SubBlockColorTable.UTF8_SUB_BLOCK_CHARS[0],
            fg: this.getNearestColor([p0]),
            bg: this.getNearestColor([p1,
          p2,
          p3])
          },
          {
            char: SubBlockColorTable.UTF8_SUB_BLOCK_CHARS[1],
            fg: this.getNearestColor([p1]),
            bg: this.getNearestColor([p0,
          p2,
          p3])
          },
          {
            char: SubBlockColorTable.UTF8_SUB_BLOCK_CHARS[2],
            fg: this.getNearestColor([p2]),
            bg: this.getNearestColor([p0,
          p1,
          p3])
          },
          {
            char: SubBlockColorTable.UTF8_SUB_BLOCK_CHARS[3],
            fg: this.getNearestColor([p3]),
            bg: this.getNearestColor([p0,
          p1,
          p2])
          },
          {
            char: SubBlockColorTable.UTF8_SUB_BLOCK_CHARS[4],
            fg: this.getNearestColor([p0,
          p3]),
            bg: this.getNearestColor([p1,
          p2])
          },
          {
            char: SubBlockColorTable.UTF8_SUB_BLOCK_CHARS[5],
            fg: this.getNearestColor([p1,
          p2]),
            bg: this.getNearestColor([p0,
          p3])
          }
        ];
        best = _.minBy(candidates, function(c) {
          return c.fg.distance + c.bg.distance;
        });
        return {
          fg: (ref = best.fg.value) != null ? ref.fg : void 0,
          bg: (ref1 = best.bg.value) != null ? ref1.bg : void 0,
          char: best.char
        };
      }

    };

    SubBlockColorTable.UTF8_SUB_BLOCK_CHARS = [
      '\u2598', // ▘ QUADRANT UPPER LEFT
      '\u259D', // ▝ QUADRANT UPPER RIGHT
      '\u2596', // ▖ QUADRANT LOWER LEFT
      '\u2597', // ▗ QUADRANT LOWER RIGHT
      '\u259A', // ▚ QUADRANT UPPER LEFT AND LOWER RIGHT
      '\u259E', // ▞ QUADRANT UPPER RIGHT AND LOWER LEFT
      '\u2588' // █ FULL BLOCK
    ];

    return SubBlockColorTable;

  }).call(this);

  render = function(image, config) {
    var colorTable, i, j, line, maxX, maxY, pixels, ref, ref1, x, y;
    colorTable = new SubBlockColorTable(config);
    // Since we go by 2, we have to end on an even index
    maxX = image.width - (image.width % 2);
    maxY = image.height - (image.height % 2);
    for (y = i = 0, ref = maxY; i < ref; y = i += 2) {
      line = [];
      for (x = j = 0, ref1 = maxX; j < ref1; x = j += 2) {
        pixels = [image.colorAt(x, y), image.colorAt(x + 1, y), image.colorAt(x, y + 1), image.colorAt(x + 1, y + 1)];
        line.push(colorTable.getNearest(pixels));
      }
      config.write(ansi.joinLineEscapes(line) + '\n');
    }
    config.write(ansi.ANSI_RESET);
  };

  module.exports = {render};

}).call(this);
