// Generated by CoffeeScript 2.7.0
(function() {
  var ANSI_COLORS_BASIC, ANSI_COLORS_EXTENDED, ANSI_COLOR_DEFAULT, ANSI_RESET, ansiEscape, chroma, convertAnsiExtended, joinLineEscapes;

  chroma = require('chroma-js');

  ansiEscape = function(code) {
    return `\x1b[${code}m`;
  };

  ANSI_RESET = ansiEscape('0');

  ANSI_COLOR_DEFAULT = {
    fg: ansiEscape('39'),
    bg: ansiEscape('40')
  };

  ANSI_COLORS_BASIC = [
    {
      color: chroma('red'),
      fg: ansiEscape('31'),
      bg: ansiEscape('41')
    },
    {
      color: chroma('yellow'),
      fg: ansiEscape('33'),
      bg: ansiEscape('43')
    },
    {
      color: chroma('green'),
      fg: ansiEscape('32'),
      bg: ansiEscape('42')
    },
    {
      color: chroma('cyan'),
      fg: ansiEscape('36'),
      bg: ansiEscape('46')
    },
    {
      color: chroma('blue'),
      fg: ansiEscape('34'),
      bg: ansiEscape('44')
    },
    {
      color: chroma('magenta'),
      fg: ansiEscape('35'),
      bg: ansiEscape('45')
    },
    {
      color: chroma('black'),
      fg: ansiEscape('30'),
      bg: ansiEscape('40')
    },
    {
      color: chroma('white'),
      fg: ansiEscape('37'),
      bg: ansiEscape('47')
    }
  ];

  // Convert an extended ANSI color code into its RGB value.
  // See: http://stackoverflow.com/questions/27159322/rgb-values-of-the-colors-in-the-ansi-extended-colors-index-17-255
  convertAnsiExtended = function(code) {
    var b, g, r;
    if (code >= 232) {
      g = (code - 232) * 10 + 8;
      return {
        color: chroma(g, g, g),
        fg: ansiEscape(`38;5;${code}`),
        bg: ansiEscape(`48;5;${code}`)
      };
    } else {
      r = Math.floor((code - 16) / 36);
      r = r > 0 ? 55 + r * 40 : 0;
      g = Math.floor(((code - 16) % 36) / 6);
      g = g > 0 ? 55 + g * 40 : 0;
      b = (code - 16) % 6;
      b = b > 0 ? 55 + b * 40 : 0;
      return {
        color: chroma(r, g, b),
        fg: ansiEscape(`38;5;${code}`),
        bg: ansiEscape(`48;5;${code}`)
      };
    }
  };

  ANSI_COLORS_EXTENDED = (function() {
    var results = [];
    for (var i = 16; i < 256; i++){ results.push(i); }
    return results;
  }).apply(this).map(convertAnsiExtended);

  joinLineEscapes = function(line) {
    var i, lastBg, lastFg, len, pixel, s;
    lastFg = null;
    lastBg = null;
    s = '';
    for (i = 0, len = line.length; i < len; i++) {
      pixel = line[i];
      if (lastBg !== pixel.bg || lastFg !== pixel.fg) {
        s += ANSI_RESET;
        if (pixel.bg != null) {
          s += pixel.bg;
        }
        if (pixel.fg != null) {
          s += pixel.fg;
        }
        lastBg = pixel.bg;
        lastFg = pixel.fg;
      }
      s += pixel.char;
    }
    if (lastBg !== null || lastFg !== null) {
      s += ANSI_RESET;
    }
    return s;
  };

  module.exports = {ANSI_RESET, ANSI_COLOR_DEFAULT, ANSI_COLORS_BASIC, ANSI_COLORS_EXTENDED, joinLineEscapes};

}).call(this);
