// Generated by CoffeeScript 2.7.0
(function() {
  var _, ansi, chroma, configure;

  chroma = require('chroma-js');

  ansi = require('./ansi-codes');

  _ = require('lodash');

  configure = function(options) {
    var alphaCutoff, ansiCodes, renderer, terminalBackground, write;
    ansiCodes = (function() {
      switch (options.colors) {
        case 'basic':
          return ansi.ANSI_COLORS_BASIC;
        case 'extended':
          return ansi.ANSI_COLORS_EXTENDED;
        default:
          throw new Error(`Unknown ANSI color space ${options.colors}`);
      }
    })();
    terminalBackground = (function() {
      switch (options.background) {
        case 'light':
          return chroma('white');
        case 'dark':
          return chroma('black');
        default:
          throw new Error(`Unknown background option ${options.background}`);
      }
    })();
    renderer = (function() {
      switch (options.mode) {
        case 'block':
          return require('./renderers/block');
        case 'shaded':
          return require('./renderers/shaded-block');
        case 'sub':
          return require('./renderers/sub-block');
        case 'braille':
          return require('./renderers/braille');
        default:
          throw new Error(`Unknown mode option ${options.mode}`);
      }
    })();
    alphaCutoff = parseFloat(options.alphaCutoff);
    write = function(str) {
      return process.stdout.write(str);
    };
    return _.extend(options, {ansiCodes, terminalBackground, alphaCutoff, renderer, write});
  };

  module.exports = configure;

}).call(this);
