// Generated by CoffeeScript 2.7.0
(function() {
  var Octree;

  Octree = (function() {
    class Octree {
      constructor(_order = 16, _center = new Octree.Point(0, 0, 0)) {
        this._order = _order;
        this._center = _center;
      }

      get(point) {
        var node;
        node = this;
        while (node.internal) {
          node = node._childAt(point);
        }
        return node._dataValue;
      }

      insert(point, value) {
        var node;
        node = this;
        while (node.internal) {
          node = node._childAt(point);
        }
        node._insert(point, value);
      }

      nearest(point, best = null) {
        var distance, halfSize, i, idx, j, startIndex;
        // Return if best is already better than anything in this node
        halfSize = Math.pow(2, this._order - 1);
        if ((best != null) && (point.x < this._center.x - halfSize - best.distance || point.x > this._center.x + halfSize + best.distance || point.y < this._center.y - halfSize - best.distance || point.y > this._center.y + halfSize + best.distance || point.z < this._center.z - halfSize - best.distance || point.z > this._center.z + halfSize + best.distance)) {
          return best;
        }
        // If we have a value, test ourselves
        if (this._dataPoint != null) {
          distance = this._dataPoint.distance(point);
          if (best == null) {
            best = {
              distance: distance,
              point: this._dataPoint,
              value: this._dataValue
            };
          } else if (distance < best.distance) {
            best = {
              distance: distance,
              point: this._dataPoint,
              value: this._dataValue
            };
          }
        }
        // Finally, recurse children starting at most likely index
        if (this._children != null) {
          startIndex = this._toChildIndex(point);
          for (i = j = 0; j < 8; i = ++j) {
            idx = (i + startIndex) % 8;
            best = this._children[idx].nearest(point, best);
          }
        }
        return best;
      }

      _internalize() {
        var i, j, quarterSize;
        this.internal = true;
        quarterSize = Math.pow(2, this._order - 2);
        this._children = new Array(8);
        for (i = j = 0; j < 8; i = ++j) {
          this._children[i] = new this.constructor(this._order - 1, this._toCenterPoint(i, quarterSize));
        }
      }

      _toCenterPoint(index, quarterSize) {
        var x, y, z;
        x = (index & 1) === 0 ? this._center.x - quarterSize : this._center.x + quarterSize;
        y = (index & 2) === 0 ? this._center.y - quarterSize : this._center.y + quarterSize;
        z = (index & 4) === 0 ? this._center.z - quarterSize : this._center.z + quarterSize;
        return new Octree.Point(x, y, z);
      }

      _toChildIndex(point) {
        var x, y, z;
        x = point.x < this._center.x ? 0 : 1;
        y = point.y < this._center.y ? 0 : 1;
        z = point.z < this._center.z ? 0 : 1;
        return z << 2 | y << 1 | x;
      }

      _childAt(point) {
        return this._children[this._toChildIndex(point)];
      }

      _insert(point, value) {
        var currentPoint, currentValue;
        // insert here if empty
        if (this._dataPoint == null) {
          this._dataPoint = point;
          this._dataValue = value;
          return;
        }
        // detect direct collisions before attempting to subdivide
        if (this._dataPoint.x === point.x && this._dataPoint.y === point.y && this._dataPoint.z === point.z) { // throw new Error('Collision', @_dataValue)
          return;
        }
        
        // otherwise we must split!
        // extract current data values
        currentPoint = this._dataPoint;
        currentValue = this._dataValue;
        delete this._dataPoint;
        delete this._dataValue;
        this._internalize();
        // re-insert both
        this._childAt(currentPoint).insert(currentPoint, currentValue);
        this._childAt(point).insert(point, value);
      }

    };

    Octree.prototype.internal = false;

    return Octree;

  }).call(this);

  Octree.Point = class Point {
    static centroid(pts) {
      var c, j, len, p;
      c = new Octree.Point();
      for (j = 0, len = pts.length; j < len; j++) {
        p = pts[j];
        c.add(p);
      }
      return c.scale(1.0 / pts.length);
    }

    constructor(x1 = 0, y1 = 0, z1 = 0) {
      this.x = x1;
      this.y = y1;
      this.z = z1;
    }

    distanceSq(p) {
      var dx, dy, dz;
      dx = p.x - this.x;
      dy = p.y - this.y;
      dz = p.z - this.z;
      return (dx * dx) + (dy * dy) + (dz * dz);
    }

    distance(p) {
      return Math.sqrt(this.distanceSq(p));
    }

    add(p) {
      this.x += p.x;
      this.y += p.y;
      this.z += p.z;
      return this;
    }

    scale(s) {
      this.x *= s;
      this.y *= s;
      this.z *= s;
      return this;
    }

    valueOf() {
      return `${this.x.toFixed(2)}, ${this.y.toFixed(2)}, ${this.z.toFixed(2)}`;
    }

  };

  module.exports = Octree;

}).call(this);
