// Generated by CoffeeScript 2.7.0
(function() {
  var PNG, Promise, chroma, createRescaledImage, fs, loadPng;

  fs = require('fs');

  ({PNG} = require('pngjs'));

  Promise = require('bluebird');

  chroma = require('chroma-js');

  loadPng = function(pngPath) {
    return new Promise(function(resolve, reject) {
      return fs.createReadStream(pngPath).pipe(new PNG({
        filterType: 4
      })).on('parsed', function() {
        return resolve(this);
      }).on('error', reject);
    });
  };

  createRescaledImage = function(png, options) {
    var charHeight, colorAt, height, ref, ref1, s, sx, sy, width, x, y;
    // default is no scaling
    width = png.width;
    height = png.height;
    x = function(i) {
      return i;
    };
    y = function(i) {
      return i;
    };
    
    // since block chars are half as wide as tall
    charHeight = (ref = (ref1 = options.renderer) != null ? ref1.charHeight : void 0) != null ? ref : 2;
    if (options.scale != null) {
      s = parseFloat(options.scale);
      sx = s * charHeight;
      sy = s;
      width = Math.floor(png.width * sx);
      height = Math.floor(png.height * sy);
      x = function(i) {
        return Math.floor(i / sx);
      };
      y = function(i) {
        return Math.floor(i / sy);
      };
    } else {
      if (options.width != null) {
        width = parseInt(options.width);
        x = function(i) {
          return Math.floor(i * png.width / width);
        };
      }
      if (options.height != null) {
        height = parseInt(options.height);
        y = function(i) {
          return Math.floor(i * png.height / height);
        };
      }
    }
    colorAt = function(xi, yi) {
      var a, b, g, idx, r;
      idx = (png.width * y(yi) + x(xi)) << 2;
      [r, g, b, a] = png.data.slice(idx, idx + 4);
      return chroma([r, g, b]).alpha((a != null ? a : 0) / 255.0);
    };
    return {width, height, colorAt};
  };

  module.exports = {loadPng, createRescaledImage};

}).call(this);
